(function(){
"use strict";
const engine=window.MusicTVEngine,catalog=window.MUSIC_CATALOG,channel=window.MUSIC_CHANNEL;
const $=id=>document.getElementById(id),els={clock:$("stationClock"),title:$("nowTitle"),artist:$("nowArtist"),slotTime:$("slotTime"),status:$("statusLine"),player:$("player"),overlay:$("intermission"),countdown:$("intermissionCountdown"),enter:$("enterButton"),play:$("playPauseButton"),live:$("liveButton"),start:$("startButton"),share:$("shareButton"),shareStatus:$("shareStatus"),next:$("nextCards"),guide:$("guideRows"),guideDate:$("guideDate"),progress:$("progressBar")};
let schedule=[],scheduleDay="",player=null,playerReady=false,apiRequested=false,entered=false,loadedKey="",endedEarly=false,lastSlotId="";const failed=new Set();
const fmtTime=ms=>new Intl.DateTimeFormat("en-US",{hour:"numeric",minute:"2-digit"}).format(new Date(ms));
const fmtDate=ms=>new Intl.DateTimeFormat("en-US",{weekday:"long",month:"long",day:"numeric"}).format(new Date(ms));
const esc=s=>String(s).replace(/[&<>\"]/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;"}[c]));
function ensureSchedule(){const key=engine.dateKey(new Date());if(key!==scheduleDay){scheduleDay=key;schedule=engine.scheduleFor(new Date(),catalog,channel.id,failed);renderGuide()}}
function art(v){return `https://i.ytimg.com/vi/${encodeURIComponent(v.videoId)}/hqdefault.jpg`}
function renderGuide(){els.guideDate.textContent=`${fmtDate(schedule[0].startsAtMs)} · new rotation at midnight`;els.guide.innerHTML=schedule.map(item=>`<article class="guide-row" data-id="${item.id}"><time>${fmtTime(item.startsAtMs)}</time><img loading="lazy" src="${art(item.video)}" alt=""><div><strong>${esc(item.video.artist)} — ${esc(item.video.title)}</strong><span>${item.video.year} · ${esc(item.video.genre)}</span></div></article>`).join("")}
function renderNext(state){const items=[];for(let n=1;n<=6;n++)items.push(schedule[(state.index+n)%schedule.length]);els.next.innerHTML=items.map(item=>`<article class="next-card"><img loading="lazy" src="${art(item.video)}" alt=""><div><time>${fmtTime(item.startsAtMs)}</time><strong>${esc(item.video.title)}</strong><span>${esc(item.video.artist)}</span></div></article>`).join("")}
function showIntermission(state){els.overlay.hidden=false;els.countdown.textContent=`${Math.max(0,state.intermissionRemaining)} sec until the next video`;if(playerReady&&loadedKey!==`break:${state.slot.id}`)player.stopVideo();loadedKey=`break:${state.slot.id}`}
function loadVideo(state){if(!entered||!playerReady)return;if(endedEarly){showIntermission(state);return}els.overlay.hidden=true;const key=`${state.slot.id}:${state.slot.video.videoId}`;if(key!==loadedKey){loadedKey=key;player.loadVideoById({videoId:state.slot.video.videoId,startSeconds:state.mediaSeconds});return}if(player.getPlayerState()===YT.PlayerState.PLAYING){const drift=state.mediaSeconds-player.getCurrentTime();if(Math.abs(drift)>2.5)player.seekTo(state.mediaSeconds,true)}}
function tick(){ensureSchedule();const state=engine.resolve(Date.now(),schedule);if(state.slot.id!==lastSlotId){lastSlotId=state.slot.id;endedEarly=false;loadedKey=""}els.clock.textContent=`${fmtTime(Date.now())} local`;els.title.textContent=state.slot.video.title;els.artist.textContent=`${state.slot.video.artist} · ${state.slot.video.year}`;els.slotTime.textContent=`${fmtTime(state.slot.startsAtMs)}–${fmtTime(state.slot.endsAtMs)}`;els.status.textContent=endedEarly?"INTERMISSION · future advertising layer":"LIVE · synchronized five-minute music-video slot";els.progress.style.width=`${Math.min(100,(state.elapsed/engine.SLOT_SECONDS)*100)}%`;document.body.style.setProperty("--program-art",`url('${art(state.slot.video)}')`);document.querySelectorAll(".guide-row").forEach(r=>r.classList.toggle("current",r.dataset.id===state.slot.id));renderNext(state);if(endedEarly)showIntermission(state);else loadVideo(state)}
function loadApi(){if(apiRequested||playerReady)return;apiRequested=true;if(window.YT&&window.YT.Player){window.onYouTubeIframeAPIReady();return}const s=document.createElement("script");s.src="https://www.youtube.com/iframe_api";s.referrerPolicy="strict-origin-when-cross-origin";document.head.appendChild(s)}
function enter(){entered=true;els.enter.hidden=true;loadApi();tick()}
function joinLive(){endedEarly=false;loadedKey="";tick()}
function startVideo(){if(!entered)enter();if(playerReady){endedEarly=false;const state=engine.resolve(Date.now(),schedule);loadedKey="";player.loadVideoById({videoId:state.slot.video.videoId,startSeconds:0})}}
function toggle(){if(!playerReady)return;const s=player.getPlayerState();if(s===YT.PlayerState.PLAYING){player.pauseVideo();els.play.textContent="Play"}else{player.playVideo();els.play.textContent="Pause"}}
function localShareCredit(url){const key="starquest_music_share_v1";let data={count:0,pending:0,coins:0};try{data=JSON.parse(localStorage.getItem(key))||data}catch(_){ }data.count=(Number(data.count)||0)+1;data.pending=(Number(data.pending)||0)+1;let awarded=0;if(data.pending>=10){awarded=Math.floor(data.pending/10);data.pending%=10;data.coins=(Number(data.coins)||0)+awarded}localStorage.setItem(key,JSON.stringify(data));window.dispatchEvent(new CustomEvent("starquest:share-progress",{detail:{progressToNextCoin:data.pending,awarded,balance:data.coins}}));return{...data,awarded}}
async function share(){const state=engine.resolve(Date.now(),schedule),payload={title:`${channel.name} · ${state.slot.video.artist} — ${state.slot.video.title}`,text:`Watching ${state.slot.video.artist} — ${state.slot.video.title} live on ${channel.name}.`,url:location.href};if(!navigator.share){try{await navigator.clipboard.writeText(payload.url);els.shareStatus.textContent="Link copied."}catch(_){els.shareStatus.textContent="Sharing unavailable."}return}try{await navigator.share(payload);const credit=localShareCredit(payload.url);els.shareStatus.textContent=credit.awarded?"Shared · 1 StarCoin completed!":`Shared · StarCoin ${credit.pending}/10`}catch(e){if(!e||e.name!=="AbortError")els.shareStatus.textContent="Share did not complete."}}
window.onYouTubeIframeAPIReady=function(){player=new YT.Player("player",{width:"100%",height:"100%",playerVars:{playsinline:1,controls:0,rel:0,modestbranding:1,enablejsapi:1,origin:location.origin,widget_referrer:location.href},events:{onReady:()=>{playerReady=true;player.unMute();player.setVolume(100);tick()},onStateChange:e=>{els.play.textContent=e.data===YT.PlayerState.PLAYING?"Pause":"Play";if(e.data===YT.PlayerState.PLAYING&&player.getDuration()>engine.SLOT_SECONDS){const state=engine.resolve(Date.now(),schedule);failed.add(state.slot.video.videoId);scheduleDay="";loadedKey="";player.stopVideo();setTimeout(tick,200);return}if(e.data===YT.PlayerState.ENDED){endedEarly=true;showIntermission(engine.resolve(Date.now(),schedule))}},onError:()=>{const state=engine.resolve(Date.now(),schedule);failed.add(state.slot.video.videoId);scheduleDay="";endedEarly=false;loadedKey="";setTimeout(tick,200)}}})};
els.enter.addEventListener("click",enter);els.play.addEventListener("click",toggle);els.live.addEventListener("click",joinLive);els.start.addEventListener("click",startVideo);els.share.addEventListener("click",share);ensureSchedule();tick();setInterval(tick,1000);
})();